# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKJnW5NMhoSo0RqVEiIUkdqFQ_zjE-PP

#**Cardiac Arrest Data Analysis(Python Project)**

📋 Dataset Overview
1.   Rows: 1,025
2.   Columns: 14
3.   Target Column: target — Likely indicates presence (1) or absence (0) of heart disease.
4.   Includes features like:
  

*   age, sex, cp (chest pain type), trestbps (resting BP), chol (cholesterol), fbs (fasting blood sugar)
*   restecg, thalach (max heart rate), exang (exercise-induced angina)
*   oldpeak, slope, ca (major vessels), thal
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the uploaded dataset
df = pd.read_csv('/content/drive/MyDrive/cardiac arrest/cardiac arrest dataset.csv')
df.head()

df.info()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

basic_stats = df.describe()
basic_stats

"""**Basic Exploration Summary**

📊 Basic Statistics:


*   Average Age: ~54.4 years
*   Average Maximum Heart Rate (thalach): ~149 bpm
*   Cholesterol (chol): Mean ~246 mg/dL, with a high outlier up to 564
*   Target values are balanced: about 51% have heart disease (1)

❌ Missing Values:
There are no missing values in any column.
"""

missing_values = df.isnull().sum()
missing_values

"""**Visual Analysis**"""

# 1. Distribution of Age, Thalach, Cholesterol
fig, axs = plt.subplots(1, 3, figsize=(18, 5))
sns.histplot(df['age'], kde=True, ax=axs[0], color="skyblue")
axs[0].set_title("Age Distribution")

sns.histplot(df['thalach'], kde=True, ax=axs[1], color="lightgreen")
axs[1].set_title("Max Heart Rate (thalach) Distribution")

sns.histplot(df['chol'], kde=True, ax=axs[2], color="salmon")
axs[2].set_title("Cholesterol Distribution")

plt.tight_layout()
plt.show()

"""**📈 Insights from Distribution Plots**


1.   Age: Most patients are between 45–65 years.
2.   Max Heart Rate (thalach): Most values range from 130–170 bpm, which aligns with typical stress-test results.
3.   Cholesterol: Distribution is skewed, with some outliers above 400 mg/dL, which may indicate risk.

**Correlation Heatmap**
"""

# Calculate correlation matrix
correlation_matrix = df.corr()

# Plot heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap="coolwarm", square=True)
plt.title("Correlation Heatmap of Cardiac Dataset")
plt.show()

"""**🔥 Correlation Heatmap Insights**


*   thalach (max heart rate) has a strong negative correlation with target → Lower max heart rate is often linked to heart disease.
*   cp (chest pain type) shows a positive correlation with target → Certain chest pain types are associated with heart disease.
*   exang (exercise-induced angina) has a strong negative correlation with target → If angina is triggered during exercise, risk is higher.
*   oldpeak, ca, slope, and thal also show notable relationships with the target.

**Visual Comparison of Key Features by Heart Disease Status (target)**
"""

# Create a figure with subplots
fig, axs = plt.subplots(1, 3, figsize=(18, 5))

# Max Heart Rate by Target
sns.boxplot(data=df, x='target', y='thalach', ax=axs[0], palette="Set2")
axs[0].set_title("Max Heart Rate vs Target")
axs[0].set_xlabel("Heart Disease (0 = No, 1 = Yes)")
axs[0].set_ylabel("Max Heart Rate (thalach)")

# Cholesterol by Target
sns.boxplot(data=df, x='target', y='chol', ax=axs[1], palette="Set1")
axs[1].set_title("Cholesterol vs Target")
axs[1].set_xlabel("Heart Disease (0 = No, 1 = Yes)")
axs[1].set_ylabel("Cholesterol (mg/dL)")

# Chest Pain Type by Target
sns.countplot(data=df, x='cp', hue='target', ax=axs[2], palette="pastel")
axs[2].set_title("Chest Pain Type vs Target")
axs[2].set_xlabel("Chest Pain Type")
axs[2].set_ylabel("Count")
axs[2].legend(title="Heart Disease")

plt.tight_layout()
plt.show()

"""**📊 Comparative Insights by Heart Disease Status (target)**


1.   Max Heart Rate (thalach): Patients with heart disease (target = 1) tend to have higher max heart rates, suggesting their heart compensates more during exertion.

2.   Cholesterol (chol): Distribution is less distinct, but some patients with high cholesterol appear in both groups—chol alone may not be a strong predictor.

3.   Chest Pain Type (cp): Certain chest pain types (especially type 1 & 2) are more frequent among heart disease patients.




"""

